# Generated by Django 4.1.4 on 2023-01-08 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('firstname', models.CharField(max_length=30, verbose_name='Имя')),
                ('midname', models.CharField(max_length=30, verbose_name='Отчество')),
                ('bday', models.CharField(max_length=30, verbose_name='Дата рождения')),
                ('profession', models.CharField(max_length=50, verbose_name='Профессия')),
                ('division', models.CharField(max_length=50, verbose_name='Структурное подразделение')),
                ('adress', models.CharField(max_length=150, verbose_name='Структурное подразделение')),
            ],
            options={
                'verbose_name': 'Worker',
                'verbose_name_plural': 'Workers',
            },
        ),
    ]
