# Generated by Django 4.1.4 on 2023-01-11 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workers',
            name='exam',
            field=models.DateField(null=True, verbose_name='Дата текущей проверки знаний'),
        ),
        migrations.AddField(
            model_name='workers',
            name='manager',
            field=models.CharField(choices=[('ОРСМУ1', 'начальник ОРСМУ Буковский С.А.'), ('ОРСМУ2', 'заместитель начальника ОРСМУ Волохов Д.В.'), ('ОРСМУ3', 'производитель работ ОРСМУ Носко Ю.М.'), ('МПУ', 'начальник Мирского производственного участка Дрик П.А.'), ('УМК', 'начальник участка металла и камня Смольский Д.Ю.'), ('УД', 'начальник участка деревообработки Знак С.Н.'), ('НБ', 'Не было'), ('ДР', 'Другой')], default='default title', max_length=150, verbose_name='Руководитель стажировки'),
        ),
        migrations.AddField(
            model_name='workers',
            name='medical',
            field=models.DateField(null=True, verbose_name='Дата текущего мед. осмотра'),
        ),
        migrations.AddField(
            model_name='workers',
            name='training_end',
            field=models.DateField(null=True, verbose_name='Дата окончания стажировки'),
        ),
        migrations.AddField(
            model_name='workers',
            name='training_start',
            field=models.DateField(null=True, verbose_name='Дата начала стажировки'),
        ),
    ]
