# Generated by Django 4.1.4 on 2023-01-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_workers_exam_workers_manager_workers_medical_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workers',
            name='manager',
            field=models.CharField(choices=[('ОРСМУ1', 'начальник ОРСМУ Буковский С.А.'), ('ОРСМУ2', 'заместитель начальника ОРСМУ Волохов Д.В.'), ('ОРСМУ3', 'производитель работ ОРСМУ Носко Ю.М.'), ('МПУ', 'начальник Мирского производственного участка Дрик П.А.'), ('УМК', 'начальник участка металла и камня Смольский Д.Ю.'), ('УД', 'начальник участка деревообработки Знак С.Н.'), ('НБ', 'Не было'), ('ДР', 'Другой')], default='Не было', max_length=150, verbose_name='Руководитель стажировки'),
        ),
    ]
