# Generated by Django 4.1.4 on 2023-01-11 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0003_alter_workers_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workers',
            name='adress',
            field=models.CharField(max_length=150, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='workers',
            name='manager',
            field=models.CharField(choices=[('начальник ОРСМУ Буковский С.А.', 'начальник ОРСМУ Буковский С.А.'), ('заместитель начальника ОРСМУ Волохов Д.В.', 'заместитель начальника ОРСМУ Волохов Д.В.'), ('производитель работ ОРСМУ Носко Ю.М.', 'производитель работ ОРСМУ Носко Ю.М.'), ('начальник Мирского производственного участка Дрик П.А.', 'начальник Мирского производственного участка Дрик П.А.'), ('начальник участка металла и камня Смольский Д.Ю.', 'начальник участка металла и камня Смольский Д.Ю.'), ('начальник участка деревообработки Знак С.Н.', 'начальник участка деревообработки Знак С.Н.'), ('Не было', 'Не было'), ('Другой', 'Другой')], default='Не было', max_length=150, verbose_name='Руководитель стажировки'),
        ),
    ]
