# Generated by Django 4.1.4 on 2023-01-11 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0004_alter_workers_adress_alter_workers_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workers',
            name='exam',
            field=models.DateField(blank=True, null=True, verbose_name='Дата текущей проверки знаний'),
        ),
        migrations.AlterField(
            model_name='workers',
            name='medical',
            field=models.DateField(blank=True, null=True, verbose_name='Дата текущего мед. осмотра'),
        ),
        migrations.AlterField(
            model_name='workers',
            name='training_end',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания стажировки'),
        ),
        migrations.AlterField(
            model_name='workers',
            name='training_start',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала стажировки'),
        ),
    ]
