# Generated by Django 4.1.4 on 2023-01-11 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0005_alter_workers_exam_alter_workers_medical_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workers',
            name='adress',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='workers',
            name='bday',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='workers',
            name='division',
            field=models.CharField(choices=[('Администрация', 'Администрация'), ('ОРСМУ', 'ОРСМУ'), ('Производственная база', 'Производственная база'), ('Мирский производственный участок', 'Мирский производственный участок'), ('Участок металла и камня', 'Участок металла и камня'), ('Участок деревообработки', 'Участок деревообработки')], default='Администрация', max_length=50, verbose_name='Структурное подразделение'),
        ),
    ]
