# Generated by Django 4.1.4 on 2023-01-14 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0006_alter_workers_adress_alter_workers_bday_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalExamination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(max_length=50, verbose_name='Профессия')),
                ('dangerous_factors', models.TextField(verbose_name='Вредные и опасные факторы')),
                ('condition_class', models.FloatField(verbose_name='Класс условий труда')),
                ('frequency', models.CharField(choices=[('1 раз в 2 года', '1 раз в 2 года'), ('1 раз в год', '1 раз в год')], max_length=20, verbose_name='Периодичность проведения медицинского осмотра')),
            ],
            options={
                'verbose_name': 'MedicalExamination',
                'verbose_name_plural': 'MedicalExaminations',
            },
        ),
    ]
