# Generated by Django 4.1.4 on 2023-01-13 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Строительный объект')),
                ('body', models.TextField(verbose_name='Наименование объекта')),
                ('contract_type', models.CharField(choices=[('по договору строительного подряда', 'по договору строительного подряда'), ('по договору строительного генподряда', 'по договору строительного генподряда'), ('по договору строительного подряда', 'по договору строительного подряда'), ('по договору', 'по договору')], max_length=100, verbose_name='Работы ведутся по:')),
                ('contract_number', models.CharField(max_length=50, verbose_name='Номер договора')),
                ('contract_date', models.DateField(verbose_name='Дата составления договора')),
                ('manager_main', models.CharField(choices=[('начальник ОРСМУ Буковский С.А.', 'начальник ОРСМУ Буковский С.А.'), ('заместитель начальника ОРСМУ Волохов Д.В.', 'заместитель начальника ОРСМУ Волохов Д.В.'), ('начальник Мирского производственного участка Дрик П.А.', 'начальник Мирского производственного участка Дрик П.А.')], max_length=100, verbose_name='Общее руководство')),
                ('manager_line', models.CharField(choices=[('производитель работ ОРСМУ Носко Ю.М.', 'производитель работ ОРСМУ Носко Ю.М.'), ('мастер строительных и монтажных работ ОРСМУ Терешков И.Е.', 'мастер строительных и монтажных работ ОРСМУ Терешков И.Е.'), ('мастер строительных и монтажных работ ОРСМУ Бондарчук П.В.', 'мастер строительных и монтажных работ ОРСМУ Бондарчук П.В.'), ('мастер строительных и монтажных работ ОРСМУ Потапчик С.Н.', 'мастер строительных и монтажных работ ОРСМУ Потапчик С.Н.'), ('производитель работ Мирского производственного участка Вайцехович В.Н.', 'производитель работ Мирского производственного участка Вайцехович В.Н.')], max_length=250, verbose_name='Линейный руководитель')),
            ],
            options={
                'verbose_name': 'Site',
                'verbose_name_plural': 'Sites',
            },
        ),
    ]
